spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8081/auth-server/
          filters:
            - MyLog=true
          predicates:
            - Path=/auth-server/**